import {
    Activity,
    ArrowRight,
    Ban,
    Bell,
    BookUser,
    Check,
    CheckCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    Command,
    Download,
    Eye,
    FileInput,
    Files,
    FileWarning,
    FileX2,
    Filter,
    Folder,
    FolderOpen,
    FolderSync,
    Forward,
    HelpCircle,
    LayoutDashboard,
    ListChecks,
    Loader2,
    LogIn,
    LogOut,
    Pause,
    PauseCircle,
    Pencil,
    PencilLine,
    PenSquare,
    Printer,
    Search,
    Settings,
    Siren,
    StopCircle,
    Trash,
    Unlock,
    User,
    X,
    File,
    MoreHorizontal,
    UserCog2,
    Plus,
    MoreVertical,
    ChevronLast,
    ChevronFirst,
    FolderCog,
    FileType,
    Info,
    FileText,
    Users2,
    UserCheck2,
    UserX2,
} from "lucide-react";

const Icons = {
    userX: UserX2,
    userCheck: UserCheck2,
    users: Users2,
    fileText: FileText,
    info: Info,
    fileType: FileType,
    chevronFirst: ChevronFirst,
    chevronLast: ChevronLast,
    plus: Plus,
    folderCog: FolderCog,
    userCog: UserCog2,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    filter: Filter,
    search: Search,
    folderOpen: FolderOpen,
    transfer: FolderSync,
    abort: Ban,
    unlock: Unlock,
    logo: Command,
    close: X,
    user: User,
    arrowRight: ArrowRight,
    settings: Settings,
    pause: Pause,
    documents: Files,
    incoming: LogIn,
    outgoing: LogOut,
    checkCheck: CheckCheck,
    pending: PauseCircle,
    terminal: StopCircle,
    listChecks: ListChecks,
    chevronRight: ChevronRight,
    folder: Folder,
    dashboard: LayoutDashboard,
    notification: Bell,
    chevronLeft: ChevronLeft,
    helpCircle: HelpCircle,
    activity: Activity,
    pencilLine: PencilLine,
    loading: Loader2,
    chevronDown: ChevronDown,
    chevronsUpDown: ChevronsUpDown,
    trash: Trash,
    download: Download,
    myDocuments: BookUser,
    draft: PenSquare,
    edit: Pencil,
    view: Eye,
    fileWarning: FileWarning,
    action: Siren,
    forward: Forward,
    printer: Printer,
    check: Check,
    fileInput: FileInput,
    fileX2: FileX2,
    file: File,
    sidebarTrigger: ({ className }) => (
        <svg
            className={className}
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
        </svg>
    ),
};

export default Icons;
