import {
    Activity,
    ArrowRight,
    Bell,
    BookUser,
    CheckCheck,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    Command,
    Download,
    Files,
    Folder,
    HelpCircle,
    LayoutDashboard,
    ListChecks,
    Loader2,
    LogIn,
    LogOut,
    Pause,
    PauseCircle,
    Pencil,
    PencilLine,
    PenSquare,
    Settings,
    StopCircle,
    Trash,
    User,
    X,
} from "lucide-react";

const Icons = {
    logo: Command,
    close: X,
    user: User,
    arrowRight: ArrowRight,
    settings: Settings,
    pause: Pause,
    documents: Files,
    incoming: LogIn,
    outgoing: LogOut,
    checkCheck: CheckCheck,
    pending: PauseCircle,
    terminal: StopCircle,
    listChecks: ListChecks,
    chevronRight: ChevronRight,
    folder: Folder,
    dashboard: LayoutDashboard,
    notification: Bell,
    chevronLeft: ChevronLeft,
    helpCircle: HelpCircle,
    activity: Activity,
    pencilLine: PencilLine,
    loading: Loader2,
    chevronDown: ChevronDown,
    chevronsUpDown: ChevronsUpDown,
    trash: Trash,
    download: Download,
    myDocuments: BookUser,
    draft: PenSquare,
    finalized: CheckSquare,
    edit: Pencil,
};

export default Icons;
