import {
    Activity,
    ArrowRight,
    Bell,
    CheckCheck,
    ChevronLeft,
    ChevronRight,
    Command,
    Files,
    Folder,
    HelpCircle,
    LayoutDashboard,
    ListChecks,
    LogIn,
    LogOut,
    Pause,
    PauseCircle,
    PencilLine,
    Settings,
    StopCircle,
    User,
    X,
} from "lucide-react";

const Icons = {
    logo: Command,
    close: X,
    user: User,
    arrowRight: ArrowRight,
    settings: Settings,
    pause: Pause,
    documents: Files,
    incoming: LogIn,
    outgoing: LogOut,
    checkCheck: CheckCheck,
    pending: PauseCircle,
    terminal: StopCircle,
    listChecks: ListChecks,
    chevronRight: ChevronRight,
    folder: Folder,
    dashboard: LayoutDashboard,
    notification: Bell,
    chevronLeft: ChevronLeft,
    helpCircle: HelpCircle,
    activity: Activity,
    pencilLine: PencilLine,
};

export default Icons;
