import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card.jsx";
import { useReactToPrint } from "react-to-print";
import React, { useRef } from "react";
import { Button } from "@/Components/ui/button.jsx";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/Components/ui/table.jsx";
import dayjs from "dayjs";
import { Head } from "@inertiajs/react";
import Icons from "@/Components/Icons.jsx";
import BaniLogo from "@/Components/BaniLogo.jsx";
import { transferStatuses } from "@/config/badgesColorMap.js";
import { Badge } from "@/Components/ui/badge.jsx";

const filtersKeyMapping = {
    category: "Search by",
};

const filtersValueMapping = {
    status: {
        pending: "Pending",
        completed: "Completed",
    },
    date_name: {
        transferred_at: "Date Transferred",
        completed_at: "Date Completed",
    },
    order: {
        asc: "Ascending",
        desc: "Descending",
    },
    sortBy: {
        transferred_at: "Date Transferred",
        completed_at: "Date Completed",
    },
    category: {
        tracking_code: "Document Code",
        sender: "Sender",
        receiver: "Receiver",
    },
};
export default function TransferLogs({ auth, transfers, filters }) {
    const componentRef = useRef();
    const handlePrint = useReactToPrint({
        content: () => componentRef.current,
    });

    const dateGenerate = new Date();

    return (
        <div className="mx-auto mt-10 w-[216mm] space-y-4">
            <Head title="Transfer Logs Report" />
            <Button onClick={handlePrint}>Print Report</Button>
            <Card ref={componentRef}>
                <CardHeader>
                    <CardTitle className="relative text-center">
                        <p className="flex items-center justify-center text-3xl">
                            <Icons.logo className="h-10 w-10" />{" "}
                            <span className="ml-1">Trackument</span>
                        </p>
                        <p className="mt-6"> Transfer Logs Report</p>
                        <BaniLogo className="absolute left-0 top-0 h-20 w-20" />
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-end">
                        Generated by:{" "}
                        <span className="font-bold">{auth.user.name}</span>
                    </p>
                    <p className="text-end">
                        Date:{" "}
                        <span className="font-bold">
                            {dateGenerate.toDateString()}
                        </span>
                    </p>
                    <h4 className="text-xl font-bold">Filters Applied:</h4>
                    <div className="flex flex-wrap gap-6">
                        {Object.entries(filters)
                            .filter(([key, value]) => {
                                const keysToExclude = ["perPage"];

                                return !keysToExclude.includes(key);
                            })
                            .map(([key, value]) => {
                                return (
                                    <div className="p-2" key={key}>
                                        <div className="uppercase">
                                            {filtersKeyMapping?.[key] ||
                                                key ||
                                                "Not specified"}
                                            :
                                        </div>
                                        <div>
                                            {filtersValueMapping?.[key]?.[
                                                value
                                            ] ||
                                                value ||
                                                "Not specified"}
                                        </div>
                                    </div>
                                );
                            })}
                    </div>
                    <p className="mt-4">Total Rows: {transfers.length}</p>
                    <Table className="mt-4">
                        <TableHeader className="bg-secondary">
                            <TableRow>
                                <TableHead>Document Code</TableHead>
                                <TableHead>Status</TableHead>
                                <TableHead>Date Transferred</TableHead>
                                <TableHead>Date Completed</TableHead>
                                <TableHead>Sender</TableHead>
                                <TableHead>Receiver</TableHead>
                            </TableRow>
                        </TableHeader>

                        <TableBody>
                            {transfers.map((transfer, idx) => (
                                <TableRow key={idx}>
                                    <TableCell>
                                        {transfer?.document?.tracking_code}
                                    </TableCell>
                                    <TableCell className="capitalize">
                                        <Badge
                                            className="capitalize"
                                            variant={
                                                transferStatuses[
                                                    transfer.status
                                                ]
                                            }
                                        >
                                            {transfer.status}
                                        </Badge>
                                    </TableCell>
                                    <TableCell>
                                        {transfer?.transferred_at &&
                                            dayjs(
                                                transfer.transferred_at,
                                            ).format("MMM DD YYYY hh:mm A")}
                                    </TableCell>
                                    <TableCell>
                                        {transfer?.completed_at
                                            ? dayjs(
                                                  transfer.transferred_at,
                                              ).format("MMM DD YYYY hh:mm A")
                                            : "N/A"}
                                    </TableCell>
                                    <TableCell>
                                        {transfer?.sender?.name}
                                    </TableCell>
                                    <TableCell>
                                        {transfer?.receiver?.name ||
                                            transfer?.receiver_name}
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
}
